### PR TITLE
Added Russian translation and AdwAboutWindow

### PR DESCRIPTION
**Pull request by alexkdeveloper**
Hi!
An excellent and very useful application!
The Russian translation does not work without config.vapi, so I had to add it)

### CODE REVIEW

**Comment by alexkdeveloper** [comment]
Probably, in order for the test build to be successful, you need to specify ubuntu 22.10 in workflows

**Comment by Darazaki** [comment]
Hi! Thanks a lot for your contribution :D

Looks like `Adw.AboutWindow` is only supported with libadwaita 1.2.0 and later but my computer & CI doesn't have this version yet (stuck to 1.1.0) :/

Would you be fine with me adding `Adw.AboutWindow` as an opt-in compilation option?

Also it's weird that the Russian translation requires a VAPI file since the constants should get defined inside a Vala file, maybe that's an issue on my part. I'll look into it

**Comment by Darazaki** [comment]
Ok, everything is working now! Your contributions will be included with v2.3.1 which should appear on Flathub in a few hours

I didn't manage to see why the Russian translation didn't work without a VAPI file but everything seems to be working on my end without it. Maybe your IDE didn't like the automatically generated Vala file?

Anyways, thanks again for your PR! :D

**Comment by alexkdeveloper** [comment]
Thanks!
First I built flatpak in Builder without this file. I installed it into the system (Ubuntu 22.10) and the translation into Russian did not appear, but everything worked with the vapi file. That's why I included this in the request. 
There were also no problems with libadwaita, since in the 43rd version of the platform it is in the latest stable version.

**Comment by Darazaki** [comment]
Oh I thought you meant that you were having a build error

Yeah I had the same issue at first too but after uninstalling and doing a clean build + install the Russian translation started working. Maybe it has something to do with Flatpak's "smart" partial locale installation?

Flatpak can be a bit buggy on the dev side in my experience that's why I prefer doing native builds while programming

Also fyi I've enabled `Adw.AboutDialog` in Flatpak builds since, as you said, it works perfectly with with GNOME Platform version 43 ;)

**Comment by alexkdeveloper** [comment]
Installed the update. Everything works!

Снимок экрана от 2022-12-11 10-45-07

**Pull request merged**
